POST http://localhost:3000/api/route
Content-Type: application/x-www-form-urlencoded


email = newmrtr55ail@.com &
firstName = morgan &
lastName = dgagfg &
username = he33lartrlo &
password = 12ee345nrfg
