POST http://localhost:3000/api/route
Content-Type: application/x-www-form-urlencoded


email = newmdfasrtr55ail@.com &
firstName = morgan &
lastName = dgagfg &
username = he33deflartrlo &
password = 12ee345nrfg
