import {prevMatchStats} from "../../../data/prevMatchStats";

export default function handler(req: any, res: any) {
    if (req.method === "GET") {
        res.status(200).json(prevMatchStats)
        } else if (req.method === "POST"){
            const match = req.body.match;
            const newMatch = {
                id: Date.now(),
                playerName: match.playerName,
                opponentName: match.opponentName,
                courtType: match.courtType,
                location: match.location,
                setting: match.setting,
                matchType: match.matchType,
                notes: match.notes,
                percentPointsWonOnBaseline: 40,
                percentBaselinePointsWon: 60,
                percentPointsWonByWinnersOnBaseline: 30,
                percentPointsLostByUnforcedErrorOnBaseline: 10,
                pointsWonByForehandOnBaseline:5,
                pointsWonByForehandWinnerOnBaseline: 6,
                pointsWonByBackhandOnBaseline: 9,
                pointsWonByBackhandWinnerOnBaseline: 10,
                pointsLostByForehandOnBaseline: 5,
                pointsLostByForehandUnforcedErrorOnBaseline: 8,
                pointsLostByBackhandOnBaseline: 6,
                pointsLostByBackhandUnforcedErrorOnBaseline: 7,
                forehandAccuracyOnBaseline: 20,
                backhandAccuracyOnBaseline: 60,
                percentPointsWonAtNet: 60,
                percentNetPointsWon: 40,
                percentPointsWonByWinnersAtNet: 30,
                percentPointsLostByUnforcedErrorAtNet: 20,
                forehandVolleyAccuracy: 40,
                backhandVolleyAccuracy: 40,
                overheadAccuracy: 30,
                pointsWonByForehandVolley: 20,
                pointsWonByForehandVolleyWinner: 30,
                pointsWonByBackhandVolley: 39,
                pointsWonByBackhandVolleyWinner: 30,
                pointsWonByOverhead: 30,
                pointsWonByOverheadWinner: 10,
                pointsLostByForehandVolley: 4,
                pointsLostByForehandVolleyUnforcedError: 3,
                pointsLostByBackhandVolley: 1,
                pointsLostByBackhandVolleyUnforcedError: 30,
                pointsLostByOverhead:3,
                pointsLostByOverheadUnforcedError: 0,
                percentOfTotalPointsWonOnServe: 20,
                percentOfServingPointsWon: 20,
                firstServePercentage: 80,
                secondServePercentage: 90,
                totalAces: 2,
                notReturnedServesDeuceSide: 9,
                notReturnedServesAdSide: 10,
                totalNotReturnedFirstServes: 20,
                totalNotReturnedSecondServes: 30,
                totalNotReturnedServes: 4,
                notReturnedServesToAlley: 2,
                notReturnedServesToBody: 3,
                notReturnedServesToCenter: 7,
                percentOfTotalPointsWonOnReturn: 30,
                percentOfReturnPointsWon: 4,
                missedSecondServeReturns: 6,
                missedFirstServeReturns: 7,
            }
            res.status(201).json(newMatch);
        }
}